# 
#  ___  _                          _    _  _        _
# | __|| |_  ___  _ _  _ _   __ _ | |  | \| | __ _ | |_  _  _  _ _  ___
# | _| |  _|/ -_)| '_|| ' \ / _` || |  | .` |/ _` ||  _|| || || '_|/ -_)
# |___| \__|\___||_|  |_||_|\__,_||_|  |_|\_|\__,_| \__| \_,_||_|  \___|
#                   version 2.0  (supports 1.14*)
#                        created by Masstrix
# 
#      A plugin to enhance the survival gameplay aspect and bring
#           new elements into the game for players to enjoy.
# 
# Join the offical discord to recieve updates, suggest ideas and give feedback
# at https://discord.gg/Uk3M9Y6
# 
# Visit the wiki here https://github.com/Masstrix/Eternal-Nature/wiki for more help.
# 
# Auto Plant
#   set any value to 0 to disable auto planting for a specific item.
# Render
#  style - sets where the item is displayed. This can be set to ACTIONBAR or BOSSBAR.
#  flash - sets if the value will flash when critical.
# 
version: 2
general:
  check-for-updates: true
  notify-update-join: true
global:
  waterfalls: true
  falling-leaves: true
  randomly-spread-trees: true
  auto-plant:
    play-sound: true
    enabled: true
    replant-crops: true
    saplings: 0.6
    wheet: 1.0
    carrot: 1.0
    potato: 1.0
    melon: 0.8
    pumpkin: 0.8
    beetroot: 1.0
    sweet_berry: 1.0
    flowers: 0.2
  hydration:
    enabled: true
    lose-from-walking: true
    cause-damage: true
  temperature:
    enabled: true
    cause-damage: true
    sprinting: true
    catch-fire: true
    sweat: true
    save-data: false
render:
  hydration:
    style: ACTIONBAR
    flash: true
  temperature:
    style: ACTIONBAR
    flash: true
advanced:
  update-calls: 10
  render-calls: 20
  temprature:
    scan-radius: 10
    dynamic: true
    precision: 1
messages:
  death-heat: "%name% burnt to a crisp"
  death-cold: "%name% died of hypothermia"
  death-dehydrate: "%name% died of dehydration"