# 
#  ___  _                          _    _  _        _
# | __|| |_  ___  _ _  _ _   __ _ | |  | \| | __ _ | |_  _  _  _ _  ___
# | _| |  _|/ -_)| '_|| ' \ / _` || |  | .` |/ _` ||  _|| || || '_|/ -_)
# |___| \__|\___||_|  |_||_|\__,_||_|  |_|\_|\__,_| \__| \_,_||_|  \___|
#                   version 2.0  (supports 1.14*)
#                        created by Masstrix
# 
#      A plugin to enhance the survival gameplay aspect and bring
#           new elements into the game for players to enjoy.
# 
# Join the offical discord to recieve updates, suggest ideas and give feedback
# at https://discord.gg/Uk3M9Y6
# 
# Visit the wiki here https://github.com/Masstrix/Eternal-Nature/wiki for more help.
# 
# Auto Plant
#   set any value to 0 to disable auto planting for a specific item.
# Render
#  style - sets where the item is displayed. This can be set to ACTIONBAR or BOSSBAR.
#  flash - sets if the value will flash when critical.
# 
version: 2

general:
  check-for-updates: true
  notify-update-join: true
  
global:
  waterfalls: true
  falling-leaves: true
  randomly-spread-trees:
    enabled: true
    range: 20
    scans: 2
  age-items: true
  auto-plant:
    play-sound: true
    enabled: true
    replant-crops: true
    saplings: 0.6
    wheet: 1.0
    carrot: 1.0
    potato: 1.0
    melon: 0.8
    pumpkin: 0.8
    beetroot: 1.0
    sweet_berry: 1.0
    flowers: 0.2
    
hydration:
  enabled: true
  increase-from-activity: true
  damage-when-empty: true
  display:
    style: BOSSBAR
    warning-flash: true

temperature:
  enabled: true
  cause-damage: true
  increase-from-sprinting: true
  burn: true
  freeze: true
  sweat: true
  cold-damage: -5
  heat-damage: 50
  display:
    text: "%temperature% %temp_icon% %temp_simple%"
    style: BOSSBAR
    warning-flash: true
  advanced:
    use-blocks: false
    use-biomes: true
    use-envronment: true
    block-generate-method: chunk
    save-chunk-data: false
    thread-limit: 20
    chunk-pool-cap: 20
    
messages:
  death-heat: "%name% burnt to a crisp"
  death-cold: "%name% died of hypothermia"
  death-dehydrate: "%name% died of dehydration"