name: EternalNature
main: me.masstrix.eternalnature.EternalNature
version: 2.0
author: Masstrix
api-version: 1.13

commands:
  eternalnature:
    aliases:
      - en
    permission: "eternalnature.cmd.admin"
  hydrate:
    permission: "eternalnature.cmd.hydrate"
  test:
