name: EternalNature
main: me.masstrix.eternalnature.EternalNature
version: 2.0.1
author: Masstrix
api-version: 1.14

commands:
  eternalnature:
    aliases:
      - en
    permission: "eternalnature.cmd.admin"
  hydrate:
    permission: "eternalnature.cmd.hydrate"
  test:
