# 
#  ___  _                          _    _  _        _
# | __|| |_  ___  _ _  _ _   __ _ | |  | \| | __ _ | |_  _  _  _ _  ___
# | _| |  _|/ -_)| '_|| ' \ / _` || |  | .` |/ _` ||  _|| || || '_|/ -_)
# |___| \__|\___||_|  |_||_|\__,_||_|  |_|\_|\__,_| \__| \_,_||_|  \___|
#                        created by Masstrix
# 
#      A plugin to enhance the survival gameplay aspect and bring
#           new elements into the game for players to enjoy.
# 
# Join the offical discord to recieve updates, suggest ideas and give feedback
# at https://discord.gg/Uk3M9Y6
# 
# Visit the wiki here https://github.com/Masstrix/Eternal-Nature/wiki for more help.
# 
# 
version: 2

general:
  check-for-updates: true
  notify-update-join: true
  language: "en"
  
global:
  wind:
    enabled: true
    gusts:
      enabled: true
      chance: 1.0
      max-strength: 1.0
      push-players: true
      push-entities: true
      show-particles: true
  falling-leaves:
    only-spawn-from-natrual-leaves: true
    enabled: true
    range: 12
    fidelity: 3
    max-particles: 300
    scan-delay: 2
    spawn-chance: 0.005
  randomly-spread-trees:
    enabled: true
    range: 20
    scans: 2
  age-items: true
  auto-plant:
    enabled: true
    play-sound: true
    replant-crops: true
    saplings: 0.6
    wheat: 1.0
    carrot: 1.0
    potato: 1.0
    melon: 0.8
    pumpkin: 0.8
    beetroot: 1.0
    sweet-berry: 1.0
    flowers: 0.2
    
hydration:
  enabled: true
  increase-from-activity: true
  sweat: true
  damage:
    enabled: true
    amount: 0.5
    delay: 2000
  display:
    enabled: true
    style: BOSSBAR
    warning-flash: true
    format: "%flash%H²O %data% %effects%"
    icon:
      ico: "⭘"
      normal:
        full: "aqua"
        half: "cyan"
        empty: "gray"
      thirsty:
        full: "green"
        half: "dark green"
        empty: "gray"
  drink-from-open-water: true
  thirst-effect:
    enabled: true
    amount: 0.1
  consumables:
    water_bottle: 2
    potion: 1.5
    milk_bucket: 5
    cooked_beef: 0.5
    cooked_pork: 0.5
    cooked_chicken: 0.5
    cooked_rabbit: 0.5
    cooked_mutton: 0.5
    cooked_cod: 0.5
    cooked_salmon: 0.5
    bread: -1
    honey_bottle: 1
    melon_slice: 1
    mushroom_stew: 2
    rabbit_stew: 1.5
    beetroot_soup: 2
    dried_kelp: -0.3
    cookie: -0.1
    apple: 0.5
    golden_apple: 0.5
    enchanted_golden_apple: 2

temperature:
  enabled: true
  max-delta-change: 15
  damage:
    enabled: true
    amount: 1.0
    delay: 1000
    threshold:
      cold: -5
      heat: 60
  display:
    enabled: true
    format: "%temperature% %temp_icon% %temp_name%"
    use-rgb-colors: true
    icon-match-method: LINEAR
    style: BOSSBAR
    warning-flash: true
  scanning:
    use-blocks: true
    use-biomes: true
    use-weather: true
    use-items: true
    use-environment: true
    advanced:
      area: 11
      height: 5

icons:
  temperature:
    burning:
      icon: "☀"
      temp: 60
    hot:
      icon: "☀"
      temp: 30
    warm:
      icon: "✿"
      temp: 25
    pleasant:
      icon: "✿"
      temp: 15
    cool:
      icon: "✿"
      temp: 5
    cold:
      icon: "❈"
      temp: 0
    freezing:
      icon: "❄"
      temp: -5
  weather:
    clear:
      icon: "☀"
      color: "&a"
    cloudy:
      icon: "☁"
      color: "&7"
    raining:
      icon: "☔"
      color: "&b"
    thunder:
      icon: "⛈"
      color: "&e"