# 
#  ___  _                          _    _  _        _
# | __|| |_  ___  _ _  _ _   __ _ | |  | \| | __ _ | |_  _  _  _ _  ___
# | _| |  _|/ -_)| '_|| ' \ / _` || |  | .` |/ _` ||  _|| || || '_|/ -_)
# |___| \__|\___||_|  |_||_|\__,_||_|  |_|\_|\__,_| \__| \_,_||_|  \___|
#                        created by Masstrix
# 
#      A plugin to enhance the survival gameplay aspect and bring
#           new elements into the game for players to enjoy.
# 
# Join the offical discord to recieve updates, suggest ideas and give feedback
# at https://discord.gg/Uk3M9Y6
# 
# Visit the wiki here https://github.com/Masstrix/Eternal-Nature/wiki for more help.
# 
# Auto Plant
#   set any value to 0 to disable auto planting for a specific item.
# Render
#  style - sets where the item is displayed. This can be set to ACTIONBAR or BOSSBAR.
#  flash - sets if the value will flash when critical.
# 
version: 2

general:
  check-for-updates: true
  notify-update-join: true
  language: "en"
  
global:
  falling-leaves:
    enabled: true
    range: 12
    fidelity: 3
    max-particles: 300
    scan-delay: 100
    spawn-chance: 0.005
  randomly-spread-trees:
    enabled: true
    range: 20
    scans: 2
  age-items: true
  auto-plant:
    play-sound: true
    enabled: true
    replant-crops: true
    saplings: 0.6
    wheet: 1.0
    carrot: 1.0
    potato: 1.0
    melon: 0.8
    pumpkin: 0.8
    beetroot: 1.0
    sweet_berry: 1.0
    flowers: 0.2
  render-delay-ticks: 20
    
hydration:
  enabled: true
  increase-from-activity: true
  damage-when-empty: true
  display:
    style: BOSSBAR
    warning-flash: true

temperature:
  enabled: true
  sweat: true
  max-delta-change: 15
  damage:
    enabled: true
    damage-dealt: 1.0
    damage-delay: 1000
    threshold:
      cold: -5
      heat: 60
  display:
    text: "%temperature% %temp_icon% %temp_simple%"
    style: BOSSBAR
    warning-flash: true
  scanning:
    use-blocks: true
    use-biomes: true
    use-weather: true
    use-items: true
    use-environment: true