#
#  ___  _                          _    _  _        _
# | __|| |_  ___  _ _  _ _   __ _ | |  | \| | __ _ | |_  _  _  _ _  ___
# | _| |  _|/ -_)| '_|| ' \ / _` || |  | .` |/ _` ||  _|| || || '_|/ -_)
# |___| \__|\___||_|  |_||_|\__,_||_|  |_|\_|\__,_| \__| \_,_||_|  \___|
#                        created by Masstrix
#
#                        TEMPERATURE SETTINGS
#
# Biome specific atmosphere ground level temperature.
# Biome names do not need to be exact and will match to the closest name.
options:
  direct-sun-amplifier: 1.3
  cave-modifier: 0.7
  global-scalar: 4
  biome-default-temp:
    morning: 10
    mid_day: 18
    dusk: 15
    mid_night: 12

data:
  weather:
    clear: 0
    rain: -3
    storm: -5

  biomes:
    ocean: 10
    deep_ocean: 8
    frozen_ocean: -3
    cold_ocean: 4
    lukewarm_ocean: 14
    warm_ocean: 18

    river: 13
    frozen_river: -3

    beach:
      morning: 10
      mid_day: 18
      dusk: 15
      mid_night: 12

    plains:
      morning: 10
      mid_day: 18
      dusk: 15
      mid_night: 12
    swamp*:
      morning: 16
      mid_day: 24
      dusk: 20
      mid_night: 18

    mountains: 2
    mountains_edge: 6
    snowy_mountains: -5

    savanna*:
      morning: 13
      mid_day: 25
      dusk: 20
      mid_night: 14

    jungle*:
      morning: 25
      mid_day: 35
      dusk: 30
      mid_night: 20
    jungle_edge*:
      morning: 20
      mid_day: 28
      dusk: 24
      mid_night: 18

    badlands*:
      morning: 15
      mid_day: 34
      dusk: 25
      mid_night: 10

    desert*:
      morning: 15
      mid_day: 40
      dusk: 30
      mid_night: -3

    frozen*: -3
    taiga*: -5
    snowy*: -8
    ice*: -10

    # Nether Biomes
    nether: 20
    nether_wastes: 20
    crimson_forest: 13
    warped_forest: 18
    soul_sand_valley: 15
    basalt_deltas: 25

    # End Biomes
    end: -10

  blocks:
    lava:
      emission: 2
      falloff: 3
    fire:
      emission: 10
      falloff: 2
    torch:
      emission: 2
      falloff: 2
    redstone_torch:
      emission: 1
      falloff: 1
    campfire:
      emission: 5
      falloff: 3

    lantern:
      emission: 1
      falloff: 2
    jack_o_lantern:
      emission: 20
      falloff: 2

    snow:
      emission: -0.1
      falloff: 1
    snow_block:
      emission: -0.1
      falloff: 1
    ice:
      emission: -0.1
      falloff: 1
    forsted_ice:
      emission: -0.1
      falloff: 1
    packed_ice:
      emission: -0.3
      falloff: 1
    blue_ice:
      emission: -0.5
      falloff: 2

    spawner:
      emission: 2
      falloff: 1

    # Nether Items
    nether_portal:
      emission: 5
      falloff: 2
    glowstone:
      emission: 1
      falloff: 2

    # End Items
    end_stone:
      emission: -0.1
      falloff: 1
    end_portal:
      emission: -3
      falloff: 3


  clothing:
    turtle_helmet: 0.4

    leather_helmet: 1
    leather_chestplate: 2.2
    leather_leggings: 1.8
    leather_boots: 0.5

    iron_helmet: 0.3
    iron_chestplate: 1.3
    iron_leggings: 1
    iron_boots: 0.3

    gold_helmet: 0.3
    gold_chestplate: 1.3
    gold_leggings: 1
    gold_boots: 0.3

    diamond_helmet: 0.3
    diamond_chestplate: 1.3
    diamond_leggings: 1
    diamond_boots: 0.3

cache:
  min-temp: 0.0
  max-temp: 0.0