#
#  ___  _                          _    _  _        _
# | __|| |_  ___  _ _  _ _   __ _ | |  | \| | __ _ | |_  _  _  _ _  ___
# | _| |  _|/ -_)| '_|| ' \ / _` || |  | .` |/ _` ||  _|| || || '_|/ -_)
# |___| \__|\___||_|  |_||_|\__,_||_|  |_|\_|\__,_| \__| \_,_||_|  \___|
#                        created by Masstrix
#
#                        TEMPERATURE SETTINGS
#
# Biome specific atmosphere ground level temperature.
# Biome names do not need to be exact and will match to the closest name.
options:
  direct-sun-amplifier: 1.3
  cave-modifier: 0.7
  time-modifier: true
  global-scalar: 4
  biome-default-temp: 13

data:
  weather:
    clear: 0
    rain: -5
    storm: -8
  
  biomes:
    ocean: 10
    frozen_ocean: -10
    cold_ocean: 2
    warm_ocean: 18
    plains: 13
    beach: 10
    swamp: 17
    snowy_mountains: -5
    mountain: 2
    mountain_edge: 6
    savanna: 25
    jungle: 30
    badlands: 34
    jungle_edge: 
      6000: 25
    desert:
      morning: 0
      mid_day: 40
      dusk: 0
      mid_night: -3
    desert_hills: 42
    frozen: -3
    tiga: -5
    snowy: -8
    ice: -10
    end: -10
    river: 12
    nether: 50
    
  blocks:
    lava:
      emission: 50
      falloff: 6
    fire:
      emission: 30
      falloff: 3
    torch:
      emission: 10
      falloff: 2
    redstone_torch:
      emission: 2
    campfire:
      emission: 20
      falloff: 2
    lantern:
      emission: 20
      falloff: 2
    glowstone:
      emission: 20
      falloff: 2
    netherrack:
      emission: 20
      falloff: 2
    jack_o_lantern:
      emission: 20
      falloff: 2
    snow:
      emission: 20
      falloff: 2
    snow_block:
      emission: 20
      falloff: 2
    ice:
      emission: -1
      falloff: 2
    forsted_ice:
      emission: -1
      falloff: 2
    packed_ice:
      emission: -1.5
      falloff: 2
    blue_ice:
      emission: -1.8
      falloff: 2
    end_stone:
      emission: -3
      falloff: 2
    end_portal:
      emission: -5
      falloff: 2
    nether_portal:
      emission: 20
      falloff: 2

  clothing:
    turtle_helmet: 1
    leather_helmet: 2
    leather_chestplate: 3
    leather_leggings: 3
    leather_boots: 1
    
    iron_helmet: 1
    iron_chestplate: 2
    iron_leggings: 1
    iron_boots: 0
    
    gold_helmet: 1
    gold_chestplate: 3
    gold_leggings: 2
    gold_boots: 1
    
    diamond_helmet: 1
    diamond_chestplate: 2
    diamond_leggings: 2
    diamond_boots: 1
    
cache:
  min-temp: 0
  max-temp: 0